sudo: required
services:
  - docker


before_install:
  - docker build -t ksondz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ksondz/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "react-app"
  env: "reactApp-env"
  bucket_name: "elasticbeanstalk-eu-west-3-102833267024"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_VALUE"
  secret_access_key: "$AWS_SECRET_KEY_VALUE"

